---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 1h
  values:
    fullnameOverride: renovate-operator
    auth:
      oidc:
        enabled: true
        existingSecret: renovate-operator-oidc-credentials
        issuerUrl: https://id.davidstewen.com/application/o/renovate-operator/
        secretKey: RENOVATE_OPERATOR_CLIENT_SECRET

    metrics:
      enabled: true
      serviceMonitor:
        # -- whether to create a ServiceMonitor for the operator metrics
        enabled: true
        # -- scrape interval for the ServiceMonitor, defaults to Prometheus global scrape interval
#        interval: ~
      dashboard:
        # -- whether to create a Grafana dashboard for the operator metrics
        enabled: true
        annotations: {}
        labels:
          grafana_dashboard: "true"
        # -- namespace to create the dashboard in, defaults to the release namespace
#        namespace: ~
    webhook:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: renovate-operator-oidc-credentials
      valuesKey: RENOVATE_OPERATOR_CLIENT_ID
      targetPath: auth.oidc.clientId
