apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/<schematic-id>:v1.14.0
provisioning:
  diskSelector:
    match: disk.serial == "22061X806791"
  wipe: false
