---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng-mcp
spec:
  image: docker.io/isokoliuk/mcp-searxng:2.1.0@sha256:fab95f98b28726ab9668cbe2d4db045a65b873a55fbc43e704f5d4ec5738144a
  groupRef:
    name: mcp-tools
  env:
    - name: SEARXNG_URL
      value: https://search.davidstewen.com
  transport: stdio
