---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng-mcp
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.8.0@sha256:787626c360cc00559093416bc701bf029075615da0c67b7026e6bc11c7386f19
  groupRef:
    name: mcp-tools
  env:
    - name: SEARXNG_URL
      value: https://search.davidstewen.com
  transport: stdio
