---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng-mcp
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.12.1@sha256:4b305aaeb8b5d091cd4d4e8471b013b9474d02a6c642e48c4c8d0abb7d5bc853
  groupRef:
    name: mcp-tools
  env:
    - name: SEARXNG_URL
      value: https://search.davidstewen.com
  transport: stdio
