apiVersion: v1
kind: Pod
metadata:
  name: multus-multi-net-poc
  namespace: home
  annotations:
    #   # DO NOT ENABLE
    #   # Enabling this adds an extra default route to the container. My IoT network is locked down tight and results in failed external DNS lookups
    #   # k8s.v1.cni.cncf.io/networks: home-automation-iot-dhcp
    k8s.v1.cni.cncf.io/networks: |
      [{
        "name":"iot",
        "namespace": "network",
        "ips": ["172.16.20.106/24"],
        "mac": "aa:e9:02:a4:7e:79"
      }]
spec:  # specification of the pod's contents
  containers:
  - name: multus-multi-net-poc
    image: "busybox"
    command: ["top"]
    stdin: true
    tty: true
