---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localai-local-ai-models
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 200Gi
