apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/<schematic-id>:v1.14.0
provisioning:
  diskSelector:
    match: disk.serial == "BTHH811211KF512D"  # Check the serial
  wipe: false
