---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-xunholy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-xunholy-secret
    template:
      data:
#        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
#        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        OPENCLAW_GATEWAY_PASSWORD: "{{ .OPENCLAW_GATEWAY_PASSWORD }}"
        SLACK_APP_TOKEN: "{{ .SLACK_OPENCLAW_APP_TOKEN }}"
        SLACK_BOT_TOKEN: "{{ .SLACK_OPENCLAW_BOT_USER_OAUTH_TOKEN }}"
        SLACK_BOT_USER_OAUTH_TOKEN: "{{ .SLACK_BOT_USER_OAUTH_TOKEN }}"
#        SLACK_SIGNING_SECRET: "{{ .SLACK_OPENCLAW_APP_SIGNING_SECRET }}"
        SLACK_TALOS_HOMELAB_APP_TOKEN: "{{ .SLACK_TALOS_HOMELAB_APP_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
    - extract:
        key: slackapi
