apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SJEVTrtLpAiXl5iNqA5U,iv:yh2/QmCSB6XkWefXq6MTR2saE0R5gbRa2t7BERWsJ/0=,tag:up6Pc3gQweyPgbSbbNr+dw==,type:str]
  SVC_MC_ADDR: ENC[AES256_GCM,data:R/kpFhhAUmL5tFkyzw==,iv:fgcvvdaHdwvlVknMbgfAB/oW800cxQDBdFVvWkrF6TQ=,tag:7BSdpeVzAGo+EuB6JUeY6Q==,type:str]
  SVC_MQTT_ADDR: ENC[AES256_GCM,data:w/cBq3VyAhoVHZb6jQ==,iv:O0hVHwJ0d8VqVn10EXHiERMeRR3EJv278uBamwgctTw=,tag:o5ObTa/goMKnH0ivNRk4OA==,type:str]
  PI3B_IP: ENC[AES256_GCM,data:lldVjXweM24XUwKAfA==,iv:EakbnSHmRdYk5yop694GsoSICrd+WGa/npZcjMdWwEU=,tag:2IuQhzvRHqGaRoUmTM5l6g==,type:str]
  SVC_HASS_ADDR: ENC[AES256_GCM,data:nOMd4IE4yui2zin+UA==,iv:MLurdMGc1BwdYF5P4ZmUjMIBbR/JZfqD6yeqtylW6nw=,tag:Fvxi2oX6kA2JD+TLIuoiqg==,type:str]
  SVC_PLEX_ADDR: ENC[AES256_GCM,data:lfVgeoSPgLGIY0D26g==,iv:cEKz3m7gBQTutAFT//UkBjmW+GwxTfh9AWLAStlyWbQ=,tag:MwVTKMkfljBHOw+gLi/Pfw==,type:str]
  SVC_POSTGRES16_ADDR: ENC[AES256_GCM,data:8oJA2FJz6exVXg8sGw==,iv:wQ6qf2BfmYbhpWbBlZabeUqrmICPh065iUNwPeMY2xU=,tag:3/XYbpu6MxjSod2aOokk9g==,type:str]
  SVC_POSTGRES17_ADDR: ENC[AES256_GCM,data:ut6GTVoA7Tk12x0HAg==,iv:/YQ4cjLo0ixQVs+mL7vTsFDXnWqhQmB6gjJxVeD3sFk=,tag:R7VfI/Bgbks9DRThRYfTew==,type:str]
  SVC_POSTGRES18_ADDR: ENC[AES256_GCM,data:alzSisngWHPL/zK8EQ==,iv:gl/Tu3oEzCX2e9Orkrj3hKPvnii/XPL+6uLjNYxMijo=,tag:Rc89NyduR0xuM/wFtrHkTw==,type:str]
  SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:PVSWmPiwYPwTcOvJhw==,iv:LqGLZBhlCWV9/KfaFKiY6lVqU2pMwiJwfByJcjPzuII=,tag:eMT92hYLcbDdrQTygILX0w==,type:str]
  SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:9W2szlNyhr6BbOWxrg==,iv:A+8bAIjFFTBO1tBZ1YRqzESjPkSZkdNkQYtP4JMHeEU=,tag:qK+YBdKTHYb7Zwnwcr0nhg==,type:str]
  SVC_SMTP_ADDR: ENC[AES256_GCM,data:+oc3lYmPX6eek0WPeg==,iv:7kodm4Dj1wSMKJCZ8A4lc11W6fAxdZajWoflyJgQYaU=,tag:jBtUHfi44czxahLneFGXQw==,type:str]
  SVC_UNIFI_ADDR: ENC[AES256_GCM,data:pV4bJpc7lRfd1nEtVQ==,iv:52wthQyc9SnJbaH4dP0VtrLM6U6WGL44kiaGNTYBa6w=,tag:uih2/oeiLl1F5oz9yoxVgA==,type:str]
  SVC_WYOMING_PIPER_ADDR: ENC[AES256_GCM,data:MICKQKg7Lvy19TpSQw==,iv:olLWSWo8DiKvDrvuygELNheNKMLknxZGbEwHc6+no+M=,tag:Zhcamvj0UxCiRyxhjkMatA==,type:str]
  SVC_WYOMING_WHISPER_ADDR: ENC[AES256_GCM,data:KJ2avie6Dc5ORimItg==,iv:NBflR9AILNcLZefaMcu52GIwH731hpuPgzh1Ofto7KQ=,tag:lxN/Nf3gvSbIoT4qd3wubQ==,type:str]
  SVC_WYOMING_WAKEWORD_ADDR: ENC[AES256_GCM,data:eRmShLTM4Q65IgsSxw==,iv:jFnngxhDWrzHr2jpJPJA8tsXH9IW4MEn0dTMF7FLpQ4=,tag:kUjwx6SHlP3lJY3acn3A3Q==,type:str]
  SVC_FRIGATE_ADDR: ENC[AES256_GCM,data:YLQGDRCkkIqW64dBOg==,iv:VfIFuzD1ZYToL29CfQGqbA/yvD1/QFm1u3cIEmfcEyc=,tag:TOe6ENtIm07VzE+dT4ggKA==,type:str]
  SVC_BOINC_ADDR_AMD64: ENC[AES256_GCM,data:CMNO0Jp41fq2aZQCzQ==,iv:4gJL8MmOjBheIsEyY7EACMVhD01HL8nyJCYOQrp08GU=,tag:C3ajlVRi+EP8IjKyNKXjYg==,type:str]
  SVC_BOINC_ADDR_ARM64: ENC[AES256_GCM,data:QA7dg5noAKV7Wr6R2A==,iv:NKT/dLztdKF4Fb3pv7g9m2cc7CVqSVC/Ld7DwzBEy58=,tag:RYPeUPboNffWDw1GPPXqQw==,type:str]
  SVC_OLLAMA_ADDR: ENC[AES256_GCM,data:3LilHzltIf0Z0Eofvw==,iv:75OuIeqL0WKHhV3TdpXwa0pN29eoTaTF0XyXlZeTvgs=,tag:5mQRdUmjLD5PQwVabkfSBw==,type:str]
  SVC_OPENCLAW_ADDR: ENC[AES256_GCM,data:p5brAjS3t6UcYOpwfA==,iv:3BxUDjEQlKGOo8YVPb/kN0BxAkd3KTVztYSiMADz/g8=,tag:pUauumJTwb4VrU69gI2pUQ==,type:str]
  NAS_IP: ENC[AES256_GCM,data:EF0zwHhPwM8yfIX+Ww==,iv:d464giNYyVgmFIzWFHtYMmq1XurpPGA8jO5BrQ4VLIU=,tag:QE2XuyKHjl0XBJWN6MfAiQ==,type:str]
  HASS_PI4: ENC[AES256_GCM,data:QMfINHqsoPCsNTd66A==,iv:wsTledMPNz33FlOwkFbw/zybiJv9MtgvVg0zjXWjrsI=,tag:zfst7QTVwJ+1w6C9jQPTbw==,type:str]
  HASS_YELLOW: ENC[AES256_GCM,data:wepcDJxZkfswbKFZkQ==,iv:/VVvp6b4GoFH6rlBvY313pXC1O1314uxsW/jdq4JoZw=,tag:w/o6GsLKU5QIPNe6+QEAHQ==,type:str]
  PIHOLE_IP: ENC[AES256_GCM,data:HpmLLy31oSh/5/jE7RI=,iv:Qev7hv5xdEZ4Lu8W2RTe7OrUd6cWppMyLLt6UD1LJRY=,tag:ugwfGscTWQ/Ci+7TBINHRw==,type:str]
  SVC_PIHOLEK_ADDR: ENC[AES256_GCM,data:kDZwAZ9SLRNAOauoyA==,iv:wBMU3vcyIZWPHLu/3OQBMjH1p12U8Bbu3wbLMWTHi4k=,tag:wEjjkqaFc9vOa7Gf6VJgmA==,type:str]
  SYN_MINIO: ENC[AES256_GCM,data:Y5/OfTj4T0aPfd8TGwQ=,iv:ncOmTptLWDH/6Ip9mugIcrDfejkOYrwymMOeE7wqhcg=,tag:7woDkOac8KxUs2EMDsrlbQ==,type:str]
  NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:aCHwZVTkan0fjmE3Ev3OAtUXNqxS8JMO392qmMV9LE+D7SxqCLAlQB4IZw==,iv:d263Pbt5Rb0Fke89QQ2WV5fahyST0E14+KSe6VTP40o=,tag:LBmDRCBgo2GKVVSlDJMXng==,type:str]
  SVC_TDARR_ADDR: ENC[AES256_GCM,data:2dcMuOLWZ3o6c9zI7Q==,iv:u/uMV/h1jDWBXcNmFOGps1cI21kvzsgnOseIBgfVv3c=,tag:P2VimZa+dTUfjrGh/skbEQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:BUClPgm2kUMwAfkqfMojgzJubQ==,iv:nb+1eAhgM6iR9ag3DKMl/ZUu4wddUdvyNWgeABczcdc=,tag:8pyixTLQ3yBPtSFKXcTigQ==,type:str]
  SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:77lrGohWTChIS6x9dA==,iv:JbFOlCyqsKG/trfI0WjN4z2GCYalUzfpYAsNmIHP6Jg=,tag:KNRuiSpOO1LdLR9e/PapOA==,type:str]
  SVC_SYSLOG_IDS_ADDR: ENC[AES256_GCM,data:881enFeG7RQFB5BXxA==,iv:+aBqcWUpr4vp3qA9/grlgaRyDtneomStHk94pdqgH14=,tag:/Yy9znpe38zE54YxTr+mnw==,type:str]
  SVC_SEARXNG_ADDR: ENC[AES256_GCM,data:HfTYWCGr83yi1566jA==,iv:5C1MsrYH3bF+4eweji4b5lnt/yozPjfPIfIPA+7wCFY=,tag:51NLACxAt7fIPL48QpS1Mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVC9PTmRSeHAyTnVPQlVQ
        OWZjMlVXSGdXNStoYkhMVTFnYTJiUVNHaERJCmxRNGgwa0NWeXZTZzJlaFdsQVVQ
        ZzFna3NIT2Q1TTRpMGZjSUc4M0gwdWMKLS0tIDEvOVR3WkFaKzN1SU5Hcm5DVWgx
        Q05UVXZGWm5QM0JKaUlXU2dkSTYzSGsKp0ouqkGccnr0dR3FloV57gqpb0vJDm5b
        KbTBPJbi48Tf2cKe+QaerWI2y5+eh1su7vWiYJd/Y/LyBXFQUAllkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T11:33:57Z"
  mac: ENC[AES256_GCM,data:qwjHTdgNbK0egvROBAORM9RAWdGV85Jq5fTepryRqdKjdJ+jzF5xI+Q2yp2LxWVdNRR2w3rd/kJzwcoOM/VxBrLox2OrPbYB1yGc+PMnaX44yP7d6DqarNP3PC6N7tE1RHW0XxfRDFQ3/PqqbqFkLpEEsTln6ZaKkKzgkBpgqoA=,iv:yU/ikqEEQCKTU2pzROdJmSkJ3colhmqIi4KHbk3tfSM=,tag:GWdUNpIrXNjdTXpQyHJMwQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
