apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:YvqJQGExBE77gsLV74k2,iv:PD/2qKBoMZ31eiQsQF3ZjsRYrdy2NGvpCI6FpIbqzhE=,tag:kffSmX9KnpasIncqOyguaQ==,type:str]
  SVC_MC_ADDR: ENC[AES256_GCM,data:0CGOz5iV8mCnmOUObg==,iv:+wn+6Xi5AGH5fkcUGhElo3ztYt1wGcIOrDG6MZHfowA=,tag:pMk4CKKwfhFZhvMLQFuY2g==,type:str]
  SVC_MQTT_ADDR: ENC[AES256_GCM,data:AdVyIBACR9bvI1FIUg==,iv:wRpuxAtrPifveDyuRPJAw2w4a40RSCDHKn6ta90yZRc=,tag:k2ZLcQDrk2cBFrYHrHIuhQ==,type:str]
  PI3B_IP: ENC[AES256_GCM,data:MlUmozSP4RMq9wlQrw==,iv:YK7nQs3xQlTMM27xB0440PlFsdEHrdTvEo1rPZghWxA=,tag:ic7Utq+KVdiYBOTYW1KK5A==,type:str]
  SVC_HASS_ADDR: ENC[AES256_GCM,data:UmXlzbU9/leBza8T3w==,iv:OEzjY19FCh0GI63Nckp7BV+xyFDu8UaeabXayWyvmo0=,tag:zTauMDxUjJ7xTgLMgq++Zg==,type:str]
  SVC_PLEX_ADDR: ENC[AES256_GCM,data:3C/3iHlChbGQQU7wQA==,iv:R74Rxrou1l3mWEDjkDPu8ympoCuPm1dnkeqM1yKkj20=,tag:nT0D+o+jicLvsxb0QkpcBg==,type:str]
  SVC_POSTGRES16_ADDR: ENC[AES256_GCM,data:gxbXj8eDZM3QGa3mkw==,iv:dvWLeTE8UDJ4IGlzqUmYYCP7ugQTUpdG+Lsj7v4SGsw=,tag:tilXzW3DhJg//29ofKkL5Q==,type:str]
  SVC_POSTGRES17_ADDR: ENC[AES256_GCM,data:H3u3VoJmseId+lIHYA==,iv:yEhXVhKozCos4mKRGURKyJWWVVO3FFKVqRg/q+uuFIE=,tag:gbUI6PBTeAOATolPpdXbtw==,type:str]
  SVC_POSTGRES18_ADDR: ENC[AES256_GCM,data:timedWJ8+ueBdz+B4A==,iv:b9FKsfC/Rik0a0nEy64MNDmT3ucQLRouEfZScFkgAkw=,tag:JiqhgMEuYSMkxjW2YMxslg==,type:str]
  SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:VEmW97wYG6048yv8SQ==,iv:5BSvEq55LRtFZFvnqu3ZuZZYZmoxZFnlisauZu0TFW0=,tag:wVpS3p2Pn9fm2zdBQLbGCQ==,type:str]
  SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:Hr20+rj7GZFQQAKTtQ==,iv:hFGFeijDfDvDWhFOR01VHpPPfI/Gw2whBLf3owNqVuc=,tag:M2o2+BQJgkWgFak5NAHgbg==,type:str]
  SVC_SMTP_ADDR: ENC[AES256_GCM,data:ujb8tEJ/ZT8p9qwR6g==,iv:cB1P4kMGGRWiAleM96tp/8z7uhz9IZQOaJpw0xuMjbE=,tag:EWDeswCndxgDt5s0RqGt+A==,type:str]
  SVC_UNIFI_ADDR: ENC[AES256_GCM,data:YLVCaeayJTFzuTYyMA==,iv:0JijRDQ6wB25egGyZYMYcBziRUmq0M9frlKsnvnZ9P8=,tag:2HNn8mJwqTjgP8SbQixfug==,type:str]
  SVC_WYOMING_PIPER_ADDR: ENC[AES256_GCM,data:RI2QVaAQEabBmZ49hQ==,iv:SUOBiZPQH+wp0vf5ITAnqzL1iXa84dNL/4PeNAnonpU=,tag:mNb49EXZNcqPjdDAoUsaLA==,type:str]
  SVC_WYOMING_WHISPER_ADDR: ENC[AES256_GCM,data:UkxqysB7IcEs4ElV8g==,iv:PuJyJSP6BlWawKTsDJ2ewJRR/bWUeIp+MI/mlrfzykc=,tag:gsHQDMll3LN1dWsG7l/T4w==,type:str]
  SVC_WYOMING_WAKEWORD_ADDR: ENC[AES256_GCM,data:ZYmMk8V2LOUCduFBIA==,iv:WCtk3nDU+8L3sQmR1AviYgmE4R6cw2ZRZ+dnshZgMrc=,tag:mJc5W2Ux5tiMjK4Uhj1wWA==,type:str]
  SVC_FRIGATE_ADDR: ENC[AES256_GCM,data:o9OMovkY5KQwd3TfwA==,iv:rjm0iIQ0VQ8f0imr+QQHcm7lceHC5uEm0mSFNYS1zrY=,tag:lMtfwnXzBhnHG2S0WmKAZA==,type:str]
  SVC_BOINC_ADDR_AMD64: ENC[AES256_GCM,data:beR9KJ2qRmfuPc7Y8A==,iv:KeI0559MTfScfiHDpg0odEXzrGwDVENeVqs/NYthNnE=,tag:Zqx6Q9w4sE0mJHRKWb+WPw==,type:str]
  SVC_BOINC_ADDR_ARM64: ENC[AES256_GCM,data:4f9qgI1Ck/wxtRgGPw==,iv:4f0+GxAIXbVhMEiiN+8tvyVfL2KYrAKXUJ2OZsOIGBM=,tag:UOed3MVSuHAnLTYmSfCKQQ==,type:str]
  SVC_OPENCLAW_ADDR: ENC[AES256_GCM,data:LBJnTnIo/nGTMlZRgw==,iv:DDqBhjhBbeswBSaqFlSTk+PwptW9jcFXy4apFbZxCOU=,tag:NdwSZOT3w55aSNsbem5Ywg==,type:str]
  NAS_IP: ENC[AES256_GCM,data:/LimJXuyuREwF8S4ig==,iv:NDrq+3p5vz3QNHN7XL3PuDZUFmQBGjFKQ3uNT7RhXis=,tag:Bvd4UyqOaoZ+2iwbgSwzxQ==,type:str]
  HASS_PI4: ENC[AES256_GCM,data:/rRSO2rRflJ8oWlXqA==,iv:nt2qwNTKCFNhen2TZHSfns9stUxsb1/ofI4MJXMsCCU=,tag:GcgTU9n1C0/uPJpAPi0NWQ==,type:str]
  HASS_YELLOW: ENC[AES256_GCM,data:IK5Q7x0SJX8kifw9OQ==,iv:L2ur4bRZqcdKlOGS+wt5X48CyMPeA31KDQKTVlVLzSQ=,tag:rSxl9RJmidiOgMtzC5b42A==,type:str]
  PIHOLE_IP: ENC[AES256_GCM,data:M4BrB15o2l77mHwUldU=,iv:IeJj832dHLhWde46g3Lc2LCM2RtvXPl73p63szhKaII=,tag:sCM2QD6725QvfYNIY9FDKA==,type:str]
  SVC_PIHOLEK_ADDR: ENC[AES256_GCM,data:FIOGhpUbezm5eL18KA==,iv:UeSN517wUXOrYedoM+r6FL+VSk3ibuaVbzql1ud8v3w=,tag:FYkk3p679pFr0ElvYQ2avg==,type:str]
  SYN_MINIO: ENC[AES256_GCM,data:3gOcUFbtQJSVbT0r4xk=,iv:LbsqfmxcciCkwlWYr+I4WYXms6pztomgT84Lxupas8k=,tag:sYznUDVMQPD7K/VpYnld2A==,type:str]
  NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:czOlnLFaK0MFxBu/J++CGJoTsvicxjMeRKdIjqb4dFLP4tDZM1brdR3h1w==,iv:mLe8IcB6WdI7N2vUCxu5F/d7BV4ofrsFG6vKRzTPO+Y=,tag:geXRvEOZEDx0ovP0Qurj9A==,type:str]
  SVC_TDARR_ADDR: ENC[AES256_GCM,data:VD7GAeFsMzsC1kLDVA==,iv:HgRPUG2mmkJ+14YobfdvSrO2RVwUiQSmuQv0/pL7x7Y=,tag:ORtRtyDHGoX5x4YFvexNbA==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:TgKNQchcZewJzXWPW95/SoMNXA==,iv:sVVCTEPZVDdWOSSOWbOTex+vvHG0BPyPEYWbZ5KVnjU=,tag:UKoWcuNx9y25KnQMf7/7dg==,type:str]
  SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:AwBUx3dnAmljf832Dw==,iv:OW/CPlnLBJZ8hdrlbmIIpo/Jq42syCedSxQSSeocwM4=,tag:iPHlp08wftkQBMlqd5XUDw==,type:str]
  SVC_SYSLOG_IDS_ADDR: ENC[AES256_GCM,data:vpHyHPxnyHWxQfqv+w==,iv:mlrb4FEA5weQy/napKY6PNwFQgLTDtDlJD4vPXBFyrE=,tag:9CafRShQW9fRRQS7O8kWxg==,type:str]
sops:
  age:
    - recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUG9wZm4xYnBBTUxReXJN
        YzBOZkpVbGZFRWRMYWl5cWViby84MmZ0alJNClBWUEUzQU9HaTA0K0hJVWlEVXBu
        SE5teStlL1BvWlAvZU5uMGFndEg1WU0KLS0tIDR3WXFWclVJTXpVYytVY0FjUWxT
        V3B6a2wrVGxwTTJ1TkE2UzdMNjNrRkkKNnt/fS+qM1uPDvJjVf1H9C836wTQxLVo
        opAa1rhKPHu7wWG8Oul4xrHtixWJhJv4C8k0fPVB78a6eDPXxvHchA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T19:30:33Z"
  mac: ENC[AES256_GCM,data:m0UkFu+aPkGoRW0InukgtUVvE0mp0EES/gg37HuslTbi1y9H5nFSFSg70elW5oIIB3i9A741UuAAd8uZyfTcpS4qID8zLkPgA7CC/DU6vFv4OyOPbgiT8ZgikCIwaTUsBbhxxb+ReK55nOsUIPiHJs0c+1iEcsMq2flTQsbeVgM=,iv:CnmX6cTWFrEn+TWTgqyrQY1I8jHUKO7vSIlk/zLGJXI=,tag:eqRVPEgb9lPxk1FYRcUrGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
