apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:vdgxm9OWyWgQs94vEgxd,iv:zgRmPQPro/Uyi5TZmDIv668oqbXG6O0UnD5Ca30uXT4=,tag:pq1y+d/no0zrLS7foVjxMA==,type:str]
  SVC_MC_ADDR: ENC[AES256_GCM,data:6c1DMkPIcUusfCEt/A==,iv:086j4PabyocOfnJZZTR8g+oEPTHVImG9j/ytWy2nrjE=,tag:eirsIiV6l12hdWPqWR4vig==,type:str]
  SVC_MC2_ADDR: ENC[AES256_GCM,data:2cdNMzsnHcyA6ECgJw==,iv:wcPytuw/WTV553zTl6/jk3rhrCGvFyo6iju4WAVo7Qc=,tag:7GEqLHpm4Y1ngamecFuH/g==,type:str]
  SVC_MQTT_ADDR: ENC[AES256_GCM,data:9rK8IFKKlfdt1TIfFQ==,iv:oOka92B/6/fT5Ggkk1vpt62kpbltnBHbKg9sQe9ND4s=,tag:MbQIh7fpVf4rVO++pj3b9w==,type:str]
  PI3B_IP: ENC[AES256_GCM,data:7x2YW7JA1zciFqzQ8Q==,iv:31sj+CoTiHOQAq6EqljnmUdKAeO78fwI6liXQZOSS6U=,tag:lg0HirKaKfccAWBj8MSTGg==,type:str]
  SVC_HASS_ADDR: ENC[AES256_GCM,data:3DmsIWPMv4ov+LgjTw==,iv:cMvlFUA6Rpf3letDMPVUXJ73/Jhvu49qdNACJXw98QM=,tag:TZTrh2FR8bKBWNZ+aGvCxg==,type:str]
  SVC_PLEX_ADDR: ENC[AES256_GCM,data:WeDcS1nHPh8U55LEZg==,iv:q8BsXEzf5zYV0Z1iAeQFwD7B9j2E+zob+anMpdt3LmI=,tag:B58xIMd5OwdTiJP3LoeY/A==,type:str]
  SVC_POSTGRES16_ADDR: ENC[AES256_GCM,data:xKB2VPU/iyeAc4eW4w==,iv:kUQSTh7clYaeAP6oi7xZ4WFss9btedXmo3meAnU/TIA=,tag:Q72g2CKpztbP3LkYRdRciw==,type:str]
  SVC_POSTGRES17_ADDR: ENC[AES256_GCM,data:DvyKr92IW2nqAVEiqw==,iv:zY/IQPyWkf59xNOKYMWq28O3wJ0a5HJba3pZRUK/49g=,tag:S/zDU/xXGtNTzx7Keg67kg==,type:str]
  SVC_POSTGRES18_ADDR: ENC[AES256_GCM,data:Or79Ne4jmDYcAIMtLQ==,iv:wEvPWEbZXH1R+D8tIICQzQeuO6iiiJmwejvHPABL+Bs=,tag:9047tePM5uyJxZjtLr70FA==,type:str]
  SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:ac8jPOkyopKyFQpEGw==,iv:icUp9Lf0Z5OioebL3JnUKMGHF1S4J6+wdDtqGW+BU/8=,tag:XC8QZHlsonKUrbmgOiQEjQ==,type:str]
  SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:ao6/3d9YZpIOvSmJGg==,iv:j/qffqeS19TGxfcIsdCbtx2UHOHvd3Q0k5xo/PuQ5CY=,tag:+ZIZ+LaYRkKl1rI6jDLv9A==,type:str]
  SVC_SMTP_ADDR: ENC[AES256_GCM,data:LG4XWZw27mHIy5Xl3Q==,iv:W40uiOXeAMuuxNb0MdL2Vb7oZ0nxRlNOPwxl8z6c7bk=,tag:13t6L+pvzueMtIO3PHj9Pw==,type:str]
  SVC_UNIFI_ADDR: ENC[AES256_GCM,data:VkvjqyIrgvL2hHzhBw==,iv:WjzKGX+dsm2k5pSgW5Ok81XLFQSnr1vAgUjmCSJSE6g=,tag:UCOI6DQ8qHk31/pvIM/+Vg==,type:str]
  SVC_WYOMING_PIPER_ADDR: ENC[AES256_GCM,data:NBSxCmL1TRJCHlByqg==,iv:tjrA/2P+Ax6bcaJ++SMcqs2qbQ9fYQlWcI9bio7fkRw=,tag:sgkg9j122SChDN9hMyqKWA==,type:str]
  SVC_WYOMING_WHISPER_ADDR: ENC[AES256_GCM,data:6hwUGtyWWriuER8eiA==,iv:e8dlbZEQcWKAO5C8fU8899bobzRoFgZVee/bRGQp1Ds=,tag:L4o3ZVp3CdydLx72ArpW+g==,type:str]
  SVC_WYOMING_WAKEWORD_ADDR: ENC[AES256_GCM,data:l35rF1Sy21S9KaR+dQ==,iv:uzXid5xiYaoOtF1MPnbOfP0bnP4GDhCw+4MMU9LC3qE=,tag:Gm1fBlh7NSZ1CUjyEusK2g==,type:str]
  SVC_FRIGATE_ADDR: ENC[AES256_GCM,data:c2flpXXW5GghjVGhWQ==,iv:ulJue78Ll1fzf2GlZ55fymikRRRSmOR6oob5ounGUUo=,tag:SnqclrVbvE/GOOmea9deug==,type:str]
  SVC_BOINC_ADDR_AMD64: ENC[AES256_GCM,data:L35NAyxVT0wyznNedQ==,iv:xRnbRJffy4tObCQ+a/tT6INxT5S/gSDtvZnfwmlqxSE=,tag:V3BPfeKR1kciKO4AtB1HfQ==,type:str]
  SVC_BOINC_ADDR_ARM64: ENC[AES256_GCM,data:/fdKULoi2ht6yDEnsw==,iv:iXxaPcBktME/Yyz/HI4DN986F7mtMBkQG6vh9wveaCc=,tag:WL1QIxMOGmcgnGdqPVteOw==,type:str]
  SVC_OLLAMA_ADDR: ENC[AES256_GCM,data:3v3B/WhNpG8Lo0MR+Q==,iv:HlgnMwLCWuwQTJ3z8rHM2q2EC9xtr7nm42Gis3W+ofA=,tag:QhE7HR64aiLi19Xoh7w8zg==,type:str]
  SVC_OPENCLAW_ADDR: ENC[AES256_GCM,data:SqW5yO0iwLr7OxA2Ww==,iv:+Y101wZvL+64iWD8IIa1xs0wzvcGebdyvd27vqi83Fo=,tag:xvnISXZUO7/W7W9sqVfxFA==,type:str]
  SVC_OPENCLAW2_ADDR: ENC[AES256_GCM,data:6Oxud9TFXg/k+Xgdxw==,iv:xq3D1mMgFPbLZuI7n8W6HXrP2bsxG1LVesX2m7Mx9BM=,tag:rJ1Pv6qXz0UMpVw40ztrpQ==,type:str]
  SVC_OTEL_COLLECTOR_ADDR: ENC[AES256_GCM,data:jb015c6qrJR7aDPBMA==,iv:laIu7vd+H7J5R5eAerFvuHn6DvEhaVGbeU0ROGNP8N4=,tag:ilJWj01a0tX0SKDqBd2gPQ==,type:str]
  NAS_IP: ENC[AES256_GCM,data:cUesaAyk1CKFMeLU8Q==,iv:5S04KxNdZGXxyZ7cey6RYwcGRy13m4OcuwSlk9AhGlw=,tag:JNj6V/v64sur0gcl6pnaAQ==,type:str]
  HASS_PI4: ENC[AES256_GCM,data:wK9qCxWcCEQFBYrfIA==,iv:YkjHt8fqHecQG2DwKvNpOH9b9ti13FgI9VgpuvvD3cw=,tag:pquj8th9hBbyxpd9CVBmRQ==,type:str]
  HASS_YELLOW: ENC[AES256_GCM,data:2FcMA5DTk2XZtcyFGw==,iv:eY9XFzbqJiAKNJ1tjtfyERGF/aD3TKS4HW9Tc2p7Af4=,tag:qa8EfOdayYtrPE5Yn0Rk+Q==,type:str]
  PIHOLE_IP: ENC[AES256_GCM,data:O0O0psNASKkxrLalChg=,iv:kRkIFtdFSi+kje/pHesm7hkke8gSz4f4PqGhu06JyTI=,tag:FEZq6Pot9SE7+oXypzCM+w==,type:str]
  SVC_PIHOLEK_ADDR: ENC[AES256_GCM,data:a4R/rNqvB5KLd78ylQ==,iv:44HeerEJof/z12F45Zk0CN6vLDLnL/asx0ULa4qh6lY=,tag:tEV1VLuQbxrA00qg71xDJw==,type:str]
  SYN_MINIO: ENC[AES256_GCM,data:U9/2urvv6dE2NySuhvU=,iv:LWYh9BSLDb2yYwMjgNXjRktkyfLTDKJTe3QqXsHGTdg=,tag:8c1mfn6WKz9nqORwEFFZJg==,type:str]
  NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:iF+UCn34E0OXN1d8JKz1RMu68wg0ZQ6zQd/MT6L6IOd0Ca8ab4amnHrFRA==,iv:vgxG8HqxWPtctOjXJZ9p7RVSG+neFaHOSpztpPowtqI=,tag:YK+As4GmDC7xdPTMFcL7Nw==,type:str]
  SVC_TDARR_ADDR: ENC[AES256_GCM,data:HoDFtKEqQLZ5vu5+9w==,iv:UUCVKDNRBEBDPX+mI16/lG5Zp1hkOlC5a5AOKiViAaM=,tag:sMAwziIqod/RFTzJEJQGhQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:v0iqkm7mJzRd0QFcNz4DnDITng==,iv:TKlIuIC0DFK+yTmCygTsTM7Fs3n1WMc6Shlk6FTwXgQ=,tag:k862D6cnWylFallA2Bl8Nw==,type:str]
  SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:JMq0bzlXwuE/m89dvg==,iv:hs8JUzjCV9bEtN3PDQL8PxYAL7PVgEWH0zM01VS/Gno=,tag:cqwHXQiKXbl2q++fb20b3w==,type:str]
  SVC_SYSLOG_IDS_ADDR: ENC[AES256_GCM,data:C7xz7kmEO64Chd1f6A==,iv:Uj83LsPRk3ksJmi+UDmG642PBZhOA4iFzqSPrzc3SYk=,tag:huY9tKU68uEw64r9dwUQcg==,type:str]
  SVC_SEARXNG_ADDR: ENC[AES256_GCM,data:JNvW7nQ5nR1Byjmfyg==,iv:50aVtdi5IQQH+DVU8VAC2a8z9XSQCb1X164ZDvsmxXg=,tag:uO7iPUIFzg1u8PRDN8bsFA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTnZRNGJnUngvdk1kUitN
        Y2djZjhlN3dvS3AyWTBONTU1R0FQSWM5S0M4CnprRjUrTkgzb3B2cUY4ZmFjMC8w
        R0RyTm16U3VPUktFRnZUYmVuV2pRbGMKLS0tIEFxYytlaWpIdVppdVBaVm5iODMv
        UlJYdnpkZ0tUZFZWZmQ3dkJ2anpJZ1UKcy4cqxTQNv20rXlxhHhFlxBns9ZIgP1q
        fq8UkBuUTfJ2WmXwjTCv4FyCK5cT2o6Rru/EsobacRp+Hq+3RYM1mQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xul3cr88zm30gjs3rg9u6lljp8sclsshxclw0tq2szt8g9fz649svn838q
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T12:07:55Z"
  mac: ENC[AES256_GCM,data:u6clsTax8HgsViqJ+z4Gvdp0h93u7ZWKwNtM8BaAZolCvDUE3+iLryl8HLuXO2jYrts6J2mV42PjygUL6AEiUhu9GMAKiXzOF8FPHgBrzJdKz4TB4HrqU/ElaV3Ba9VMUNguE4ybRPBU+ySrB27fZROUZFGNyCRFzlAe1ZgDAwY=,iv:FklXwGbzn+kTEeCjE1JGBMIqUcz0bV7IcagooxOSgOU=,tag:B6yfP7tunlrzjkSQzTO9kA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
