---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-app-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        GITHUB_COM_USER: "{{ .RENOVATE_GITHUB_COM_USER }}"
        GITHUB_COM_TOKEN: "{{ .GITHUB_TOKEN_VALUE }}"
        RENOVATE_TOKEN: "{{ .talos-renovate-operator-token }}"
  dataFrom:
    - extract:
        key: github
