---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name self-hosted-test-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: Github_Selfhosted_Runners
        property: github_app_private_key
