---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: opentelemetry-collector
  values:
    fullnameOverride: opentelemetry-collector
    mode: deployment

    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

    replicaCount: 1

    # OpenTelemetry Collector executable
    command:
      name: "otelcol-k8s"
    configMap:
      create: true
#      existingName: &name opentelemetry-collector-configmap
    serviceAccount:
      create: true
    serviceMonitor:
      enabled: true
      # additional labels for the ServiceMonitor
      extraLabels:
        release: kube-prometheus-stack
    podMonitor:
      enabled: true
    # Configuration for ports
    # nodePort is also allowed
    ports:
      otlp:
        enabled: true
        containerPort: 4317
        servicePort: 4317
#        hostPort: 4317
        protocol: TCP
        # nodePort: 30317
        appProtocol: grpc
      otlp-http:
        enabled: true
        containerPort: 4318
        servicePort: 4318
#        hostPort: 4318
        protocol: TCP
      metrics:
        # The metrics port is disabled by default. However you need to enable the port
        # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
        enabled: true
        containerPort: 8888
        servicePort: 8888
        protocol: TCP
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 512Mi
    config:
      exporters:
#        debug: {}
        prometheus:
          endpoint: "0.0.0.0:9464"
      extensions:
        # The health_check extension is mandatory for this chart.
        # Without the health_check extension the collector will fail the readiness and liveness probes.
        # The health_check extension can be modified, but should never be removed.
        health_check:
          endpoint: ${env:MY_POD_IP}:13133
      processors:
        batch: {}
        # Default memory limiter configuration for the collector based on k8s resource limits.
        memory_limiter:
          # check_interval is the time between measurements of memory usage.
          check_interval: 5s
          # By default limit_mib is set to 80% of ".Values.resources.limits.memory"
          limit_percentage: 80
          # By default spike_limit_mib is set to 25% of ".Values.resources.limits.memory"
          spike_limit_percentage: 25
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${env:MY_POD_IP}:4317
            http:
              endpoint: ${env:MY_POD_IP}:4318
        prometheus:
          config:
            scrape_configs:
              - job_name: opentelemetry-collector
                scrape_interval: 10s
                static_configs:
                  - targets:
                      - ${env:MY_POD_IP}:8888
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [prometheus]
