version: v1alpha1
debug: false
persist: true
machine:
  type: worker
  token: 3a0vkq.8325y8ju7sn81unm
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEF3VmgyV25QMTc1a1RmQ0dwbUpyckNNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQXlNRGt3TnpBd01UZGFGdzB6TmpBeU1EY3dOekF3TVRkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBZVIxWE5KcXNEaFoxWWh0b2hMdXJqcE10MlJPOGJWOGxNQjg4CkhjZnlUT3VqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVcWpRdjNBYjRqeVNXZjF1Lwp6TjdVcnJGRnRyd3dCUVlESzJWd0EwRUFWU2pmOWhKbEc2eTVsblZoVE9LcnZ3M3hSS0RmV3JQZC9kY3JYcVVsCjhQVTFyeDNKclY2NloyemVEdUkzcHZhTFVQWVhlazFzUHJZVFJTN3NUSUJhQ0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ""
  certSANs:
    - 127.0.0.1
    - 10.200.15.254
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.36.1
    extraConfig:
      serializeImagePulls: false
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 10.200.15.0/24
    disableManifestsDirectory: true
  network:
    nameservers:
      - 192.168.10.195
      - 1.1.1.1
    disableSearchDomain: true
  install:
    disk: /dev/disk/by-id/nvme-WD_Blue_SN570_500GB_220628800784
    image: factory.talos.dev/installer/de1619e16531ddff67ccb4ce636a5e3ba5197eb4fc0e8421f095ec50ce9d26a6:v1.13.3
    wipe: false
    grubUseUKICmdline: true
  files:
    - content: |
        [ NFSMount_Global_Options ]
        nfsvers=4.1
        hard=True
        nconnect=16
        noatime=True
      permissions: 0o644
      path: /etc/nfsmount.conf
      op: overwrite
    - content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
      permissions: 0o644
      path: /etc/cri/conf.d/20-customization.part
      op: create
  time:
    disabled: false
    servers:
      - 162.159.200.1
      - 162.159.200.123
  sysctls:
    fs.inotify.max_user_instances: "8192"
    fs.inotify.max_user_watches: "1048576"
    net.core.rmem_max: "7500000"
    net.core.wmem_max: "7500000"
    vm.nr_hugepages: "1024"
  features:
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
      resolveMemberNames: true
cluster:
  id: OsY1cxC6z1tg7g4NPyC0BTobkjbqTdnbtfLKOjW34os=
  secret: kDKwV2g9vUNTvZfCydRd913Uko21v5D6Z6IiHRk9mJg=
  controlPlane:
    endpoint: https://10.200.15.254:6443
  clusterName: kubernetes
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.42.0.0/16
    serviceSubnets:
      - 10.43.0.0/16
  token: 0ep8d5.msr9kxax2scrm7xw
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVMrZ0F3SUJBZ0lRR0crejJaSTJoUzY0Mk52RzBpUHNwekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNREl3T1RBM01EQXhOMW9YRFRNMk1ESXdOekEzTURBeApOMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCT2JKdW03OTVIQ1JxUy9FV1JZdDN2d0daTDZvYnR5SW54YlFTWnUydUZKek1jb01saE0yandUUjYvQUoKT2RZM0pxRVpvWURzbVpZbHo1bGEzK1Y2RDVPallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVZUlp5c1A4SnpDSjB5MDVpVkJMTzJ6T2NGeEl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU9GcWVzUHkKSFg5WEt1cHU3M2RRUk83Y0VSVXRpVDV4UlhZMUQ0ZnIrK3ZZQWlFQWtRU2lraXVib2pzZVZQSTVCVHFDaXZ6TwpTT3JqcU1IbUVodjJuQSsrY1Q0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ""
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: blade2
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client
configFiles:
  - content: |-
      MONITOR ups@192.168.10.23 1 upsmon_local mypassword secondary
      SHUTDOWNCMD "/sbin/poweroff"
    mountPath: /usr/local/etc/nut/upsmon.conf
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: bond0-m0
selector:
  match: glob("e4:5f:01:ec:16:54", mac(link.hardware_addr))
---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - bond0-m0
bondMode: active-backup
mtu: 1500
addresses:
  - address: 10.200.15.32/24
routes:
  - gateway: 10.200.15.1
    metric: 1
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.20
vlanID: 20
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.30
vlanID: 30
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.100
vlanID: 100
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.110
vlanID: 110
parent: bond0
mtu: 1500
