---
apiVersion: v1alpha1
kind: BondConfig
name: bond0
links:
  - enp2s0f0np0
  - enp2s0f1np1
bondMode: 802.3ad
miimon: 100
updelay: 200
downdelay: 200
xmitHashPolicy: layer3+4
lacpRate: fast
mtu: 1500
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: bond0
clientIdentifier: mac
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.20
vlanID: 20
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.30
vlanID: 30
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.100
vlanID: 100
parent: bond0
mtu: 1500
---
apiVersion: v1alpha1
kind: VLANConfig
name: bond0.110
vlanID: 110
parent: bond0
mtu: 1500
