---
# SecurityPolicy for Authentik forward authentication with Envoy Gateway
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}
spec:
  extAuth:
    failOpen: false
    timeout: 2s
    headersToExtAuth:
      - cookie
      - authorization
      - x-forwarded-for
      - x-forwarded-host
      - x-forwarded-proto
    http:
      backendRefs:
        - name: ak-outpost-authentik-embedded-outpost
          namespace: security
          port: 9000
      path: /outpost.goauthentik.io/auth/envoy
      headersToBackend:
        - set-cookie
        - authorization
        # Authentik user headers
        - x-authentik-username
        - x-authentik-groups
        - x-authentik-entitlements
        - x-authentik-email
        - x-authentik-name
        - x-authentik-uid
        - x-authentik-jwt
        # Authentik meta headers
        - x-authentik-meta-jwks
        - x-authentik-meta-outpost
        - x-authentik-meta-provider
        - x-authentik-meta-app
        - x-authentik-meta-version
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${EXT_AUTH_HTTPROUTE_NAME:=${APP}}
