---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
  settings.yaml: |
    # https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/ICONS.md
    # https://pictogrammers.com/library/mdi/
    # https://simpleicons.org/
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    headerStyle: clean
    hideVersion: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
    layout:
      AI:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Security:
        style: row
        columns: 2
        icon: mdi-shield-home
      Music:
        style: row
        columns: 2
        icon: mdi-speaker-multiple
      Home:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Media:
        style: row
        columns: 2
        icon: mdi-play-circle
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
      Automation:
        style: row
        columns: 3
        icon: mdi-home-automation
      Monitoring:
        style: column
        icon: mdi-monitor-eye
      Infrastructure:
        style: column
        icon: mdi-server-network
      Storage:
        style: column
        icon: mdi-database
      System:
        style: column
        icon: mdi-application
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Social:
        - Discord:
            - icon: discord.png
              href: https://discord.com/app
        - Gmail:
            - icon: gmail.png
              href: http://gmail.com
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com
        - Twitch:
            - icon: twitch.png
              href: https://twitch.tv
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com/feed/subscriptions
    - Cloud:
        - CloudFlare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - AWS Console:
            - icon: aws.png
              href: https://aws.amazon.com/console/
        - BackBlaze:
            - icon: https://raw.githubusercontent.com/chaijunkin/dashboard-icons/main/png/backblaze.png
              href: https://secure.backblaze.com/user_overview.htm
        - Terraform Cloud:
            - icon: terraform.png
              href: https://app.terraform.io
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              description: Helm Chart Search
              href: https://kubesearch.dev/
        - cm4-cluster:
            - icon: github.png
              description: Renovate Dashboard
              href: https://github.com/dstewen/cm4-cluster/issues/1
        - talos-homecluster:
            - icon: github.png
              description: Renovate Dashboard
              href: https://github.com/dstewen/talos-homecluster/issues/1

  services.yaml: |
    - Infrastructure:
        - Cloudflared:
            href: https://dash.cloudflare.com/
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}
        - Router:
            href: http://192.168.10.1
            icon: pfsense.png
        - S3400-48T6SP:
            href: http://192.168.10.3
            icon: mdi-switch
        - S3700-24T4F:
            href: http://192.168.10.2
            icon: mdi-switch
        - T1500G-10MPS:
            href: http://192.168.10.20
            icon: mdi-switch
        - Unifi:
            href: {{HOMEPAGE_VAR_UNIFI_HOST}}
            icon: unifi.png
            description: Unifi Dashboard
            widget:
              type: unifi
              url: {{HOMEPAGE_VAR_UNIFI_HOST}}
              username: {{HOMEPAGE_VAR_UNIFI_USER}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - Monitoring:
        - Home-Assistant-Status:
            href: http://192.168.10.22:8123
            icon: si-homeassistant
            widget:
              type: homeassistant
              url: http://192.168.10.22:8123
              key: {{HOMEPAGE_VAR_HASS_API_TOKEN}}
        - PiHole:
            href: http://192.168.10.195
            icon: pi-hole.png
            widget:
              type: pihole
              url: http://192.168.10.195
              key: {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}
    - Storage:
        - DSM918:
            href: http://192.168.10.15:5000/
            icon: synology-dsm.png
            widget:
              type: diskstation
              url: http://192.168.10.15:5000/
              username: {{HOMEPAGE_VAR_DSM_USER}}
              password: {{HOMEPAGE_VAR_DSM_PASSWORD}}
        - Minio:
            href: http://192.168.10.198:9001/
            icon: si-minio
        - Rook-Ceph:
            href: https://rook.davidstewen.com/
            icon: si-ceph
  widgets.yaml: |
    - search:
        provider: [google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true
    - openmeteo:
        label: Home
        latitude: {{HOMEPAGE_VAR_LATITUDE}}
        longitude: {{HOMEPAGE_VAR_LONGITUDE}}
        units: metric
        cache: 5
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  docker.yaml: ""
