---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/model_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: Model
metadata:
  name: intel-phi4
  namespace: ai
spec:
  source: https://huggingface.co/microsoft/Phi-4-mini-instruct-gguf/resolve/main/Phi-4-mini-instruct-q4_0.gguf
  format: gguf
  hardware:
    accelerator: intel
    gpu:
      enabled: true
      count: 1
      vendor: intel
      layers: -1
#      resourceClaims:
#        - name: gpu
#          resourceClaimTemplateName: llmkube-models-gpu
  resources:
    cpu: "2"
    memory: "4Gi"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/inference.llmkube.dev/inferenceservice_v1alpha1.json
apiVersion: inference.llmkube.dev/v1alpha1
kind: InferenceService
metadata:
  name: intel-phi4
  namespace: ai
spec:
  modelRef: intel-phi4
  replicas: 1
  image: ghcr.io/ggml-org/llama.cpp:server-intel@sha256:8afcb6ca062f855cee752e99cee2f5753865dd7b420e477157434aba374f11f9
  resources:
    cpu: "2"
    memory: "4Gi"
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
