---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: searxng-mcp
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.7.1@sha256:dbe29a243de16aa0b5c580f7cad086505c4c80747015abac7012e0e260c14b01
  groupRef:
    name: mcp-tools
  env:
    - name: SEARXNG_URL
      value: https://search.davidstewen.com
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - npx
          args:
            - -y
            - mcp-searxng
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
      volumes:
        - name: tmpfs
  transport: streamable-http
